version: "3.4"

services:
  mongo:
    container_name: mongodb-server-${MONGO_PORT}
    image: mongo
    ports:
      - ${MONGO_PORT}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ${MONGO_DATA_DIR}:/data/db
    restart: always
    networks:
      - database

  redis:
    container_name: redis-server-${REDIS_PORT}
    image: mongo
    ports:
      - ${REDIS_PORT}:27017
    volumes:
      - ${REIDS_DATA_DIR}:/data/db
    restart: always
    networks:
      - database

networks:
  database:
    external:
      name: database
